name: Build & Test
on:
  workflow_dispatch:
    inputs:
      filter:
        description: "Test filter" # Use tilda for contains
        default: ""
        required: false
        type: string

jobs:
  call-build:
    uses: ./.github/workflows/build.yml

  call-test:
    needs: call-build
    uses: ./.github/workflows/test.yml
    with:
      filter: ${{ inputs.filter }}
