name: Build/Test/Coverage
on:
  workflow_dispatch:
    inputs:
      filter:
        description: 'Test filter'
        required: true                
        default: 'ClassName~Controller|ClassName~Weather'
        type: string
      confirm:
        description: 'Run tests?'
        type: boolean
        default: true  
# on:
#  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Release] # Add Debug if you want to have both workflows run in parallel

    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
    env:
      Solution_Name: WeatherService.sln
      Test_Project_Path: WeatherService.Test/WeatherService.Test.csproj
      
    steps:
    - name: Echo Inputs
      run: |
          echo "User supplied: ${{ inputs.filter }} as a filter"
          echo "Run tests status: ${{ inputs.confirm }}"
    
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore local tools
      run: dotnet tool restore

    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2
    
    - name: Execute unit tests with coverage
      # run: dotnet test --filter "FullyQualifiedName~${{ inputs.filter }}"
      run: dotnet tool run dotnet-coverage collect "dotnet test --filter \"${{ inputs.filter }}\"" -f cobertura -o coverage.xml
    
    - name: Generate coverage report
      run: reportgenerator -reports:coverage.xml -targetdir:CoverageReport -reporttypes:HtmlInline

    - name: Persist the coverage report
      run: echo "Save coverage report"
