# Demo a scheduled workflow
name: Scheduled Coverage
on:
 schedule: 
   - cron: '45 19 * * *' # (19:45 - 5 = 14:15) 
jobs:
  call-build:
    uses: ./.github/workflows/build.yml

  call-test:
    needs: call-build
    uses: ./.github/workflows/test.yml
    with:
      filter: ""
