name: Test Only
on:
  workflow_call:
  workflow_dispatch:
    inputs:
      filter:
        description: "Test filter" # Use tilda for contains
        required: false
        type: string

jobs:
  call-build:
    runs-on: windows-latest
    env:
      Solution_Name: WeatherService.sln
      Test_Project_Path: WeatherService.Test/WeatherService.Test.csproj

    steps:
      - name: Echo environment variables
        shell: cmd
        run: |
          @echo off
          echo "Filter: ${{ inputs.filter }}"

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Install tools
        run: |
          dotnet tool install --local dotnet-coverage
          dotnet tool install --local dotnet-reportgenerator-globaltool

      # Add MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v2
        
      - name: List files
        run: dir /s /b
        shell: cmd

      - name: Execute all unit tests with coverage
        if: ${{ inputs.filter == '' }}
        run: dotnet tool run dotnet-coverage collect "dotnet test -c Release" -f cobertura -o coverage.xml
      
      - name: Execute specific unit tests with coverage
        if: ${{ inputs.filter != '' }}
        run: dotnet tool run dotnet-coverage collect "dotnet test -c Release --filter ${{ inputs.filter }}" -f cobertura -o coverage.xml

      - name: Generate coverage report
        run: dotnet tool run reportgenerator -reports:coverage.xml -c Release -targetdir:CoverageReport -reporttypes:HtmlInline

      - name: Persist the coverage report
        uses: actions/upload-artifact@v4
        with:
          name: CoverageReport
          path: CoverageReport
